apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fumo-k8s-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chanyou0311/fumo-k8s-platform.git
    targetRevision: main
    path: overlays/production
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
