apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cert-manager-issuer.yaml
  - argocd-application.yaml
  - metallb.yaml
  - metallb-config.yaml
patches:
  - path: patches/argocd-values.yaml
  - path: patches/headlamp-values.yaml
